#!/bin/sh
### BEGIN INIT INFO
# Provides:          aesdsocket-start-stop
# Required-Start:    $remote-fs $syslog
# Required-Stop:     $remote-fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start aesdsocket daemon
### END INIT INFO

DAEMON_PATH="/usr/bin/aesdsocket"

case "$1" in
  start)
    echo "Starting aesdsocket"
    mkdir -p /var/tmp
    $DAEMON_PATH -d
    ;;
  stop)
    echo "Stopping aesdsocket"
    pkill -f aesdsocket
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0

